DELIMITER //
CREATE FUNCTION FBUSCAPRECO(V_CODPRODUTO INT(11),
							V_DTAPAGAMENTO DATE) RETURNS float(13,2)
    DETERMINISTIC
BEGIN

DECLARE PRECO_IMOVEL FLOAT(13,2);
DECLARE VALOR_FINAL FLOAT(13,2);
DECLARE V_DATA DATE;

	    SELECT PRECO.VALOR_ATUAL
          INTO PRECO_IMOVEL
	      FROM PRECO
		 WHERE PRECO.CODPRODUTO = V_CODPRODUTO;
     
		SELECT DATE_FORMAT(V_DTAPAGAMENTO, '%D/%M/%Y') - DATE_FORMAT(CURDATE(), '%D/%M/%Y')
        INTO V_DATA;
        
        SELECT DATE_FORMAT(V_DATA, '%D') * 0.03
        INTO VALOR_FINAL;     
		 

--  END IF	
    RETURN VALOR_FINAL;
END //
DELIMITER ;