DELIMITER //
CREATE PROCEDURE SP_CADASTRA_CLIENTE(IN V_SITUACAOIMOVEL VARCHAR(1),
									  IN V_NOME VARCHAR(50),
                                      IN V_CPF VARCHAR(14),
									  IN V_CODPRODUTO INT(11),
									  IN V_DESCRICAOPROD VARCHAR(50),
                                      IN V_VALOR DECIMAL (13,2),
                                      IN V_DTAATENDIMENTO DATE,
                                      IN V_TIPOIMOVEL VARCHAR(2))
BEGIN
-- IMÓVEIS DE ALUGUEL
   
-- CADASTRA CLIENTE
	SELECT IMOVEL.SITUACAO, IMOVEL.VENDA_ALUGA, IMOVEL.DESCRICAO
	  INTO V_SITUACAOIMOVEL, V_TIPOIMOVEL, V_DESCRICAOPROD
	  FROM IMOVEL
     WHERE IMOVEL.CODIGO = V_CODPRODUTO
       AND IMOVEL.VENDA_ALUGA = 'A';
 
	IF V_SITUACAOIMOVEL = 'D' AND V_TIPOIMOVEL = 'A'  THEN
                                                                  
        INSERT INTO CLIENTE(NOME, CPF, NASCIMENTO, CIDADE, ESTADO, CEP, ENDERECO, BLOQFINANC)
             VALUES (V_NOME, V_CPF, NULL, NULL, NULL, NULL, NULL, 'N');

		INSERT INTO ATENDIMENTO(NOME, CPF, CODPRODUTO, DESCRICAOPROD, TIPO, VALOR, DTAATENDIMENTO, SITUACAO)
			 VALUES(V_NOME, V_CPF, V_CODPRODUTO, V_DESCRICAOPROD, V_TIPOIMOVEL, V_VALOR, CURDATE(), 'O');
             
             SELECT ATENDIMENTO.VALOR
               INTO V_VALOR
               FROM ATENDIMENTO
              WHERE ATENDIMENTO.CODPRODUTO = V_CODPRODUTO
                AND ATENDIMENTO.CPF = V_CPF;
             
             -- ATUALIZA ALUGUEL DO IMÓVEL NA TABELA DE IMOVEIS
        UPDATE IMOVEL
           SET IMOVEL.SITUACAO = 'A',
               IMOVEL.NOME = V_NOME,
               IMOVEL.CPF = V_CPF,
			   IMOVEL.STATUS_PAGAMENTO = ' ',
               IMOVEL.VALOR = V_VALOR
         WHERE IMOVEL.CODIGO = V_CODPRODUTO
           AND IMOVEL.VENDA_ALUGA != 'V';
        
        COMMIT;
    END IF;
    
-- TRATAMENTO PARA VENDA DE IMÓVEIS

-- CADASTRA CLIENTE 
	SELECT IMOVEL.SITUACAO, IMOVEL.VENDA_ALUGA, IMOVEL.DESCRICAO
	  INTO V_SITUACAOIMOVEL, V_TIPOIMOVEL, V_DESCRICAOPROD
	  FROM IMOVEL
     WHERE IMOVEL.CODIGO = V_CODPRODUTO
       AND IMOVEL.VENDA_ALUGA = 'V';
       
	IF V_SITUACAOIMOVEL = 'D' AND V_TIPOIMOVEL = 'V' THEN
                                                                           
        INSERT INTO CLIENTE(NOME, CPF, NASCIMENTO, CIDADE, ESTADO, CEP, ENDERECO, BLOQFINANC)
             VALUES (V_NOME, V_CPF, NULL, NULL, NULL, NULL, NULL, 'N');                                                                   

		INSERT INTO ATENDIMENTO(NOME, CPF, CODPRODUTO, DESCRICAOPROD, TIPO, VALOR, DTAATENDIMENTO, SITUACAO)
			 VALUES(V_NOME, V_CPF, V_CODPRODUTO, V_DESCRICAOPROD, V_TIPOIMOVEL, V_VALOR, CURDATE(), 'V'); 
             
             SELECT ATENDIMENTO.VALOR
               INTO V_VALOR
               FROM ATENDIMENTO
              WHERE ATENDIMENTO.CODPRODUTO = V_CODPRODUTO
                AND ATENDIMENTO.CPF =  V_CPF;
             
        -- ATUALIZA VENDA DO IMÓVEL NA TABELA DE IMOVEIS
        UPDATE IMOVEL
        SET IMOVEL.SITUACAO = 'V',
            IMOVEL.NOME = V_NOME,
            IMOVEL.CPF = V_CPF,
			IMOVEL.STATUS_PAGAMENTO = ' ',
            IMOVEL.VALOR = V_VALOR
        WHERE IMOVEL.CODIGO = V_CODPRODUTO
          AND IMOVEL.VENDA_ALUGA != 'A';
        
		COMMIT;        
    END IF;
END //
DELIMITER ;